export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
export const GET_ALL_FAIL = "GET_ALL_FAIL";

export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL";
export const GET_SINGLE_USER_RESET = "GET_SINGLE_USER_RESET";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const UPDATE_SINGLE_USER_REQUEST = "UPDATE_SINGLE_USER_REQUEST";
export const UPDATE_SINGLE_USER_SUCCESS = "UPDATE_SINGLE_USER_SUCCESS";
export const UPDATE_SINGLE_USER_FAIL = "UPDATE_SINGLE_USER_FAIL";
export const UPDATE_SINGLE_USER_RESET = "UPDATE_SINGLE_USER_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
